
UPDATE items SET type = 85, name = 'Cetro do Faraó - Comum', "desc" = 'Abra para obter: Cetro do Faraó (qualidade comum) *1' WHERE id = 1123800;
UPDATE items SET type = 85, name = 'Cetro do Faraó - Superior', "desc" = 'Abra para obter: Cetro do Faraó (qualidade excelente) *1' WHERE id = 1123801;
UPDATE items SET type = 85, name = 'Cetro do Faraó - Excelente', "desc" = 'Abra para obter: Cetro do Faraó (qualidade excelente) *1' WHERE id = 1123802;
UPDATE items SET type = 85, name = 'Cetro do Faraó - Excepcional', "desc" = 'Abra para obter: Cetro do Faraó (qualidade excelente) *1' WHERE id = 1123803;
UPDATE items SET type = 85, name = 'Cetro do Faraó - Lendário', "desc" = 'Abra para obter: Cetro do Faraó (qualidade lendária) *1' WHERE id = 1123804;
UPDATE items SET type = 85, name = 'Lâmina da Noite - Comum', "desc" = 'Abra para obter: Lâmina das Trevas (qualidade comum) *1' WHERE id = 1123805;
UPDATE items SET type = 85, name = 'Lâmina da Noite - Superior', "desc" = 'Abra para obter: Lâmina das Trevas (qualidade excelente) *1' WHERE id = 1123806;
UPDATE items SET type = 85, name = 'Lâmina da Noite - Excelente', "desc" = 'Abra para obter: Lâmina das Trevas (qualidade excelente) *1' WHERE id = 1123807;
UPDATE items SET type = 85, name = 'Lâmina da Noite - Excepcional', "desc" = 'Abra para obter: Lâmina das Trevas (qualidade excelente) *1' WHERE id = 1123693;
UPDATE items SET type = 85, name = 'Lâmina da Noite - Lendária', "desc" = 'Abra para obter: Lâmina das Trevas (qualidade lendária) *1' WHERE id = 1123694;
UPDATE items SET type = 85, name = 'Pérola de Gelo-Normal', "desc" = 'Abra para obter: Pérola de Gelo qualidade Normal*1' WHERE id = 1123605;
UPDATE items SET type = 85, name = 'Pérola de Gelo-Superior', "desc" = 'Abra para obter: Pérola de Gelo qualidade-Superior*1' WHERE id = 1123606;
UPDATE items SET type = 85, name = 'Pérola de Gelo - Excelente', "desc" = 'Abra para obter: Pérola de Gelo qualidade - Excelente*1' WHERE id = 1123607;
UPDATE items SET type = 85, name = 'Pérola de Gelo - Excepcional', "desc" = 'Abra para obter: Pérola de Gelo qualidade - Excepcional*1' WHERE id = 1123608;
UPDATE items SET type = 85, name = 'Escudo Naga-Normal', "desc" = 'Abra para obter: Escudo Naga qualidade Normal*1' WHERE id = 1123609;
UPDATE items SET type = 85, name = 'Escudo Naga - Superior', "desc" = 'Abra para obter: Escudo Naga qualidade Superior*1' WHERE id = 1123610;
UPDATE items SET type = 85, name = 'Escudo Naga - Excelente', "desc" = 'Abra para obter: Escudo Naga qualidade Excelente*1' WHERE id = 1123611;
UPDATE items SET type = 85, name = 'Escudo Naga - Excepcional', "desc" = 'Abra para obter: Escudo Naga qualidade Excepcional*1' WHERE id = 1123612;
UPDATE items SET type = 85, name = 'Coroa da Chama Vermelha-Normal', "desc" = 'Abra para obter: Coroa da Chama Vermelha qualidade Normal*1' WHERE id = 1123613;
UPDATE items SET type = 85, name = 'Coroa da Chama Vermelha-Superior', "desc" = 'Abra para obter: Coroa da Chama Vermelha qualidade Superior*1' WHERE id = 1123614;
UPDATE items SET type = 85, name = 'Coroa da Chama Vermelha - Excelente', "desc" = 'Abra para obter: Coroa da Chama Vermelha qualidade Excelente*1' WHERE id = 1123615;
UPDATE items SET type = 85, name = 'Coroa da Chama Vermelha - Excepcional', "desc" = 'Abra para obter: Coroa da Chama Vermelha qualidade Excepcional*1' WHERE id = 1123616;
UPDATE items SET type = 85, name = 'Capa de Xuan Yu-Normal', "desc" = 'Abra para obter: Capa de Xuan Yu qualidade Normal*1' WHERE id = 1123617;
UPDATE items SET type = 85, name = 'Capa de Xuan Yu-Superior', "desc" = 'Abra para obter: Capa de Xuan Yu qualidade Superior*1' WHERE id = 1123618;
UPDATE items SET type = 85, name = 'Capa de Xuan Yu - Excelente', "desc" = 'Abra para obter: Capa de Xuan Yu qualidade Excelente*1' WHERE id = 1123619;
UPDATE items SET type = 85, name = 'Capa de Xuan Yu - Excepcional', "desc" = 'Abra para obter: Capa de Xuan Yu qualidade Excepcional*1' WHERE id = 1123620;
UPDATE items SET type = 85, name = 'Pérola de Gelo - Lendária', "desc" = 'Ao abrir, você pode obter: Orbe de Gelo de Qualidade Lendária*1' WHERE id = 1123643;
UPDATE items SET type = 85, name = 'Escudo Naga - Lendário', "desc" = 'Ao abrir, você pode obter: Escudo de Naga de Qualidade Lendária*1' WHERE id = 1123644;
UPDATE items SET type = 85, name = 'Coroa da Chama Vermelha - Lendária', "desc" = 'Ao abrir, você pode obter: Coroa de Chamas Vermelhas de Qualidade Lendária*1' WHERE id = 1123645;
UPDATE items SET type = 85, name = 'Capa de Xuan Yu - Lendária', "desc" = 'Ao abrir, você pode obter: Manto de Asas Misteriosas de Qualidade Lendária*1' WHERE id = 1123646;
