
UPDATE items SET type = 92, name = 'Símbolo de Chamas', "desc" = 'Ao abrir, recebe: Selo de Chamas de qualidade Rústica x1' WHERE id = 1124222;
UPDATE items SET type = 92, name = 'Símbolo de Chamas', "desc" = 'Ao abrir, recebe: Selo de Chamas de qualidade Comum x1' WHERE id = 1124223;
UPDATE items SET type = 92, name = 'Símbolo de Chamas', "desc" = 'Ao abrir, recebe: Selo de Chamas de qualidade Excelente x1' WHERE id = 1124224;
UPDATE items SET type = 92, name = 'Símbolo de Chamas', "desc" = 'Ao abrir, recebe: Selo de Chamas de qualidade Alta x1' WHERE id = 1124225;
UPDATE items SET type = 92, name = 'Símbolo de Chamas', "desc" = 'Ao abrir, recebe: Selo de Chamas de qualidade Excepcional x1' WHERE id = 1124226;
UPDATE items SET type = 92, name = 'Símbolo de Chamas', "desc" = 'Ao abrir, recebe: Selo de Chamas de qualidade Lendária x1' WHERE id = 1124227;
UPDATE items SET type = 92, name = 'Símbolo de Gelo', "desc" = 'Ao abrir, recebe: Selo de Gelo de qualidade Rústica x1' WHERE id = 1124228;
UPDATE items SET type = 92, name = 'Símbolo de Gelo', "desc" = 'Ao abrir, recebe: Selo de Gelo de qualidade Comum x1' WHERE id = 1124229;
UPDATE items SET type = 92, name = 'Símbolo de Gelo', "desc" = 'Ao abrir, recebe: Selo de Gelo de qualidade Excelente x1' WHERE id = 1124230;
UPDATE items SET type = 92, name = 'Símbolo de Gelo', "desc" = 'Ao abrir, recebe: Selo de Gelo de qualidade Alta x1' WHERE id = 1124231;
UPDATE items SET type = 92, name = 'Símbolo de Gelo', "desc" = 'Ao abrir, recebe: Selo de Gelo de qualidade Excepcional x1' WHERE id = 1124232;
UPDATE items SET type = 92, name = 'Símbolo de Gelo', "desc" = 'Ao abrir, recebe: Selo de Gelo de qualidade Lendária x1' WHERE id = 1124233;
UPDATE items SET type = 92, name = 'Símbolo de Vento e Trovão', "desc" = 'Ao abrir, recebe: Selo de Vento e Trovão de qualidade Rústica x1' WHERE id = 1124234;
UPDATE items SET type = 92, name = 'Símbolo de Vento e Trovão', "desc" = 'Ao abrir, recebe: Selo de Vento e Trovão de qualidade Comum x1' WHERE id = 1124235;
UPDATE items SET type = 92, name = 'Símbolo de Vento e Trovão', "desc" = 'Ao abrir, recebe: Selo de Vento e Trovão de qualidade Excelente x1' WHERE id = 1124236;
UPDATE items SET type = 92, name = 'Símbolo de Vento e Trovão', "desc" = 'Ao abrir, recebe: Selo de Vento e Trovão de qualidade Alta x1' WHERE id = 1124237;
UPDATE items SET type = 92, name = 'Símbolo de Vento e Trovão', "desc" = 'Ao abrir, recebe: Selo de Vento e Trovão de qualidade Excepcional x1' WHERE id = 1124238;
UPDATE items SET type = 92, name = 'Símbolo de Vento e Trovão', "desc" = 'Ao abrir, recebe: Selo de Vento e Trovão de qualidade Lendária x1' WHERE id = 1124239;
UPDATE items SET type = 92, name = 'Símbolo de Fenda Terrestre', "desc" = 'Ao abrir, recebe: Selo de Terra de qualidade Rústica x1' WHERE id = 1124240;
UPDATE items SET type = 92, name = 'Símbolo de Fenda Terrestre', "desc" = 'Ao abrir, recebe: Selo de Terra de qualidade Comum x1' WHERE id = 1124241;
UPDATE items SET type = 92, name = 'Símbolo de Fenda Terrestre', "desc" = 'Ao abrir, recebe: Selo de Terra de qualidade Excelente x1' WHERE id = 1124242;
UPDATE items SET type = 92, name = 'Símbolo de Fenda Terrestre', "desc" = 'Ao abrir, recebe: Selo de Terra de qualidade Alta x1' WHERE id = 1124243;
UPDATE items SET type = 92, name = 'Símbolo de Fenda Terrestre', "desc" = 'Ao abrir, recebe: Selo de Terra de qualidade Excepcional x1' WHERE id = 1124244;
UPDATE items SET type = 92, name = 'Símbolo de Fenda Terrestre', "desc" = 'Ao abrir, recebe: Selo de Terra de qualidade Lendária x1' WHERE id = 1124245;
UPDATE items SET type = 92, name = 'Símbolo de Luz Sagrada', "desc" = 'Ao abrir, recebe: Selo de Luz de qualidade Rústica x1' WHERE id = 1124246;
UPDATE items SET type = 92, name = 'Símbolo de Luz Sagrada', "desc" = 'Ao abrir, recebe: Selo de Luz de qualidade Comum x1' WHERE id = 1124247;
UPDATE items SET type = 92, name = 'Símbolo de Luz Sagrada', "desc" = 'Ao abrir, recebe: Selo de Luz de qualidade Excelente x1' WHERE id = 1124248;
UPDATE items SET type = 92, name = 'Símbolo de Luz Sagrada', "desc" = 'Ao abrir, recebe: Selo de Luz de qualidade Alta x1' WHERE id = 1124249;
UPDATE items SET type = 92, name = 'Símbolo de Luz Sagrada', "desc" = 'Ao abrir, recebe: Selo de Luz de qualidade Excepcional x1' WHERE id = 1124250;
UPDATE items SET type = 92, name = 'Símbolo de Luz Sagrada', "desc" = 'Ao abrir, recebe: Selo de Luz de qualidade Lendária x1' WHERE id = 1124251;
UPDATE items SET type = 92, name = 'Símbolo de Sombra Oculta', "desc" = 'Ao abrir, recebe: Selo de Trevas de qualidade Rústica x1' WHERE id = 1124252;
UPDATE items SET type = 92, name = 'Símbolo de Sombra Oculta', "desc" = 'Ao abrir, recebe: Selo de Trevas de qualidade Comum x1' WHERE id = 1124253;
UPDATE items SET type = 92, name = 'Símbolo de Sombra Oculta', "desc" = 'Ao abrir, recebe: Selo de Trevas de qualidade Excelente x1' WHERE id = 1124254;
UPDATE items SET type = 92, name = 'Símbolo de Sombra Oculta', "desc" = 'Ao abrir, recebe: Selo de Trevas de qualidade Alta x1' WHERE id = 1124255;
UPDATE items SET type = 92, name = 'Símbolo de Sombra Oculta', "desc" = 'Ao abrir, recebe: Selo de Trevas de qualidade Excepcional x1' WHERE id = 1124256;
UPDATE items SET type = 92, name = 'Símbolo de Sombra Oculta', "desc" = 'Ao abrir, recebe: Selo de Trevas de qualidade Lendária x1' WHERE id = 1124257;
UPDATE items SET type = 92, name = 'Pacote de Selo Rústico', "desc" = 'Ao abrir, pode obter aleatoriamente: 1 selo de qualidade Rústica' WHERE id = 1124258;
UPDATE items SET type = 92, name = 'Pacote de Selo Comum', "desc" = 'Ao abrir, pode obter aleatoriamente: 1 selo de qualidade Comum' WHERE id = 1124259;
UPDATE items SET type = 92, name = 'Pacote de Selo Excelente', "desc" = 'Ao abrir, pode obter aleatoriamente: 1 selo de qualidade Excelente' WHERE id = 1124260;
UPDATE items SET type = 92, name = 'Pacote de Selo de Alta Qualidade', "desc" = 'Ao abrir, pode obter aleatoriamente: 1 selo de qualidade Alta' WHERE id = 1124261;
UPDATE items SET type = 92, name = 'Pacote de Selo Excepcional', "desc" = 'Ao abrir, pode obter aleatoriamente: 1 selo de qualidade Excepcional' WHERE id = 1124262;
UPDATE items SET type = 92, name = 'Pacote de Selo Lendário', "desc" = 'Ao abrir, pode obter aleatoriamente: 1 selo de qualidade Lendária' WHERE id = 1124263;
