// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzuvcsskhqkuyjmiuqro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dXZjc3NraHFrdXlqbWl1cXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMzg3MDksImV4cCI6MjA4NzcxNDcwOX0.PVVKq84pG92Q51QSsTLnauIGSRZy3LJ9HYh5UZ14Z9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});